const firebaseConfig={apiKey:'AIzaSyDNjVx_pn_evmMKbRTu77ShNHxpzLznkW8',authDomain:'roros-cravings.firebaseapp.com',projectId:'roros-cravings',storageBucket:'roros-cravings.firebasestorage.app',messagingSenderId:'846240897530',appId:'1:846240897530:web:7168b0d74208efd5a7ec43'};
firebase.initializeApp(firebaseConfig);const auth=firebase.auth(),db=firebase.firestore();const ADMIN_EMAIL='solidtagasogid26@gmail.com';
const $=s=>document.querySelector(s);const peso=n=>'₱'+Number(n||0).toLocaleString('en-PH');const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let unsub=null,ready=false,soundOn=localStorage.soundOff!=='1',audio=null,flashTimer=null;
function beep(){if(!soundOn)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();[0,.22,.44].forEach((d,i)=>{let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=i===1?880:660;g.gain.value=.22;o.connect(g);g.connect(audio.destination);o.start(audio.currentTime+d);o.stop(audio.currentTime+d+.16)})}catch(e){}}
function fmt(t){try{return t?.toDate?t.toDate().toLocaleString('en-PH'):''}catch(e){return''}}
function items(o){let a=Array.isArray(o.items)?o.items:[];return a.map(x=>`${esc(x.quantity||x.qty||1)}× ${esc(x.name||x.productName||'Item')}`).join('<br>')||'Order items unavailable';}
function render(docs){let arr=docs.map(d=>({id:d.id,...d.data()})).filter(o=>o.status==='Pending');$('#count').textContent=`${arr.length} Pending`;$('#orders').innerHTML=arr.length?arr.map(o=>`<article class="order"><h3>Order ${esc(o.orderId||o.id)}</h3><div class="meta"><span class="badge">Pending</span> ${esc(fmt(o.createdAt))}</div><b>${esc(o.customerName||o.name||'Customer')}</b><div class="items">${items(o)}</div><div class="total">${peso(o.total)}</div><div class="meta">${esc(o.paymentMethod||o.payment||'')} ${o.address?'<br>'+esc(o.address):''}</div></article>`).join(''):'<p class="empty">No pending orders right now.</p>';}
function start(){if(unsub)unsub();ready=false;$('#conn').textContent='Connecting…';unsub=db.collection('orders').orderBy('createdAt','desc').limit(100).onSnapshot(s=>{if(ready&&s.docChanges().some(c=>c.type==='added'&&c.doc.data().status==='Pending')){beep();$('#flash').hidden=false;clearTimeout(flashTimer);flashTimer=setTimeout(()=>$('#flash').hidden=true,12000);if(navigator.vibrate)navigator.vibrate([300,150,300]);}ready=true;render(s.docs);$('#conn').textContent='● Live';},e=>{$('#conn').textContent='Connection error';$('#orders').innerHTML='<p class="err">'+esc(e.message)+'</p>'});}
auth.onAuthStateChanged(u=>{let ok=u&&u.email===ADMIN_EMAIL;$('#login').hidden=!!ok;$('#monitor').hidden=!ok;if(ok)start();else if(unsub){unsub();unsub=null}});
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#err').textContent='';try{await auth.signInWithEmailAndPassword($('#email').value.trim(),$('#password').value)}catch(x){$('#err').textContent=x.message.replace('Firebase: ','')}};
$('#logout').onclick=()=>auth.signOut();function soundLabel(){$('#sound').textContent=soundOn?'🔊 Sound On':'🔇 Sound Off'}soundLabel();$('#sound').onclick=()=>{soundOn=!soundOn;localStorage.soundOff=soundOn?'0':'1';soundLabel();if(soundOn)beep()};
document.addEventListener('click',()=>{if(soundOn&&audio?.state==='suspended')audio.resume()},{once:true});
